### ISSUE TITLE
无法访问示例网站

### ISSUE THREAD

**Issue by ponponon** [bbdshow/qelog#1]
<img width="1332" alt="图片" src="https://user-images.githubusercontent.com/38725104/165463353-c37d22ed-83ef-4e6f-9eca-e23f4323c8e1.png">

**Comment by bbdshow** [comment]
喔，抱歉，近两天我来处理一下

**Comment by bbdshow** [comment]
@ponponon 示例地址已经更新，欢迎测试使用
